name: flfpenv
channels:
  - defaults
dependencies:
  - python-dotenv==0.21.0
  - pyyaml==6.0.1
  - requests==2.31.0
  - pandas==2.2.1
  - tqdm==4.65.0
  - matplotlib==3.8.0
  - scipy==1.12.0
  - flask==2.2.5
  - scikit-learn==1.3.0
  - colorama==0.4.6
  - pytest==7.4.0
  - pip==23.3.1
  - gitpython==3.1.37
  - numpy==1.26.4
  - pip:
      - adblockparser==0.7
      - pynpm==0.2.0
      # - pyre2 # need libre2-dev on ubuntu + root access
      - hydra-core
      - parallelbar==2.4
      - unidiff==0.5.2
      - swifter==1.4.0
      - tabulate==0.9.0
